"""initial schema

Revision ID: 89799c4a02dd
Revises:
Create Date: 2026-09-03 18:40:30.873021

Autogenerated from pmchaser/db/models.py as it stands post-refactor - this
describes the schema the live database already has, not a new one. See
this file's own db/migrations/env.py module docstring: run `alembic
stamp head` (never `upgrade head`) against the existing production DB.

Does NOT include the indexes from db/base.py's _INDEXES list
(idx_tasks_owner_id etc.) - those are raw `CREATE INDEX IF NOT EXISTS`
statements applied by _ensure_indexes() on every init_db() call, outside
SQLAlchemy's metadata/autogenerate entirely (see that function's own
docstring for why: idempotent and safe to run against a database Alembic
doesn't yet know about). Adding them here too would just be a second,
redundant path to the same state - left as the one existing mechanism.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89799c4a02dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update_id', sa.Integer(), nullable=True),
    sa.Column('assistant_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('link_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_code'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unmatched_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('candidate_task_ids', sa.String(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent', sa.String(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('reply_text', sa.String(), nullable=True),
    sa.Column('reply_received_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_status', sa.String(), nullable=True),
    sa.Column('parsed_progress_pct', sa.Integer(), nullable=True),
    sa.Column('parsed_blockers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_ins')
    op.drop_table('unmatched_messages')
    op.drop_table('tasks')
    op.drop_table('people')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
