"""Alembic environment: deliberately does NOT read sqlalchemy.url from
alembic.ini - it imports pmchaser.db.base directly, so migrations always
run against whatever PM_CHASER_DB_PATH the process actually resolves
(same .env, same default-path logic, same engine construction incl. the
WAL/busy_timeout pragmas) rather than a second, independently-configured
path that could silently drift from the real one. See db/base.py's own
module docstring for why PM_CHASER_DB_PATH is the one source of truth.

First-adoption note (read before running anything against the live DB):
this project's tables already exist in production, created by
init_db()'s Base.metadata.create_all() over several years of ad-hoc
schema changes - alembic has never run against it. The initial revision
(versions/xxxx_initial_schema.py) was autogenerated FROM that existing
schema, so it describes what's already there. Running `alembic upgrade
head` against the live DB would try to CREATE TABLE on tables that
already exist and fail. The one-time fix is `alembic stamp head`
instead - it records "this DB is already at this revision" without
running any DDL. Only databases created fresh from here on (a new dev
clone, a test fixture) should ever see `upgrade head` run the initial
revision for real. Every migration after the initial one runs normally
via `upgrade head` on both.
"""

from logging.config import fileConfig

from alembic import context

from pmchaser.db.base import engine
from pmchaser.db.models import Base  # noqa: F401 - populates Base.metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection. Not used by this
    project's actual workflow (there is always a real SQLite file to
    connect to) but kept working since it's a normal alembic entrypoint
    a future contributor might reach for."""
    context.configure(
        url=str(engine.url),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Reuses pmchaser's own engine (see module docstring) instead of
    alembic's usual engine_from_config - this is the actual connection
    main.py/init_db() would use, WAL pragmas included."""
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
